#!/bin/bash -eu

#
# Create ccache tarball...
#

. /usr/lib/uhubuild/uhubuild-common

if [ -z "${UB_CCACHE_DIR:-}" ]; then
	echo " (kihagyva)"
	exit 0
fi

find "$UB_CCACHE_DIR" -type f ! -name '*.stderr' ! -anewer "$UB_ADMINDIR/.ccache_extracted" \
  -printf '%p\000%p.stderr\000' | xargs -0 -r rm -f

find "$UB_CCACHE_DIR" -depth -mindepth 1 -type d -print0 | \
  xargs -0 -r rmdir --ignore-fail-on-non-empty

if type -p sortdir >/dev/null; then
	sortdir tar cz --owner=0 --group=0 -C "$UB_CCACHE_DIR" -f "$UHUBUILD_CCACHE_DIR/.${UB_SOURCENAME}_ccache.tar.gz.tmp" .
else
	        tar cz --owner=0 --group=0 -C "$UB_CCACHE_DIR" -f "$UHUBUILD_CCACHE_DIR/.${UB_SOURCENAME}_ccache.tar.gz.tmp" .
fi
mv "$UHUBUILD_CCACHE_DIR/.${UB_SOURCENAME}_ccache.tar.gz.tmp" "$UHUBUILD_CCACHE_DIR/${UB_SOURCENAME}_ccache.tar.gz"

rm -f "$UB_ADMINDIR/.ccache_extracted"
