#!/bin/bash -eu

#
# A tényleges fordítási lépés.
#

. /usr/lib/uhubuild/uhubuild-common

cd "$UB_COMPILEDIR"


listpackages "$UB_ADMINDIR/compile-with"
_hostname  > "$UB_ADMINDIR/compile-host"
logdate "Compile-Started"


if [ -x "$UB_SRCDIR/compile" ]; then
	"$UB_SRCDIR/compile"
fi

chmod -R u+r "$UB_COMPILEDIR" "$UB_OBJECTDIR"

logdate "Compile-Finished"
