#!/bin/bash -eu

#
# A tényleges fordítási lépés.
#

. /usr/lib/uhubuild/uhubuild-common

cd "$UB_COMPILEDIR"

for i in $(grep -r ' \-O3 ' * | sed 's/:.*//g' | sort -u);do
ub_replace -O3 -O2 $i
done

listpackages "$UB_ADMINDIR/compile-with"
_hostname  > "$UB_ADMINDIR/compile-host"
logdate "Compile-Started"


if [ -x "$UB_SRCDIR/compile" ]; then
	"$UB_SRCDIR/compile"
fi

chmod -R u+r "$UB_COMPILEDIR" "$UB_OBJECTDIR"

logdate "Compile-Finished"

times > "$UB_ADMINDIR/compile-time"
sec="$(tail -n 1 "$UB_ADMINDIR/compile-time" | sed -e 's/m/\*60\+/g' -e 's/\....s//g' -e 's/ /\+/g')"
cpu="$(grep 'cpu MHz' /proc/cpuinfo | head -n 1 | cut -d: -f2 | cut -d. -f1)"
echo "$(((sec)*cpu/1000))" > "$UB_ADMINDIR/compile-time"
