#!/bin/bash -eu

#
# Snapshot készítése a compile utáni állapotról.
#

. /usr/lib/uhubuild/uhubuild-common

if [ -z "${UB_COMPILESNAPSHOTDIR:-}" -o ! -f "$UB_SRCDIR/compile" ]; then
	echo " (kihagyva)"
	exit 0
fi

logdate "Compile-Snapshot-Created"

cd "$UB_SRCDIR"
md5sum acquire compile > "$UB_WORKDIR/md5sums"
for dir in sources patches; do
	if [ -d "$dir" ]; then
		ub_list "$dir/" -type f -print0 | sort -z | xargs -r0 md5sum >> "$UB_WORKDIR/md5sums"
	fi
done
echo "compiled" > "$UB_WORKDIR/snapshot-type"
cd "$UB_WORKDIR"
mkdir -p "${UB_COMPILESNAPSHOTDIR}"
pretendroot tar czf "${UB_COMPILESNAPSHOTDIR}/${UB_SOURCENAME}_compiled.tar.gz" \
	snapshot-type md5sums admin compile object
rm "$UB_WORKDIR"/{snapshot-type,md5sums}
