#!/bin/bash -eu

if grep -qx skip-optipng "$UB_SRCDIR/options"; then
	echo " kihagyva"
	exit 0
fi

find "$UB_INSTALLDIR" -name '*.png' -type f -print0 | \
	xargs -I '{}' -0 -P "$UB_MAKE_PROCS" -n 1 \
		bash -c \
			'optipng -q "{}" && echo "  {} OK" || echo "  {} WARNING: BAD PNG: "$(file -b "{}")""'
