#!/bin/bash -eu

#
# Postinst és postrm szkript előállítása.
#
# Minden csomag kap postinst, postrm és prerm szkriptet, amely egy adott
# szkriptet hív meg (/usr/sbin/uhu-pkg), argumentumként a teendőt (postinst,
# prerm, postrm) és a csomag nevét adva meg.
#
# Az egyetlen kivétel: az ezeket a szkripteket tartalmazó csomag (uhu-pkg)
# postrm része üres. Nyilván.
#
# Ha saját egyéni postinst, postrm vagy prerm szkript is van a csomaghoz,
# akkor az {postinst,postrm,prerm}-custom néven kerül bemásolásra. Ezt az
# /usr/sbin/uhu-pkg szkript fogja indítani.
#

. /usr/lib/uhubuild/uhubuild-common

cd "$UB_PACKAGEDIR"

for pkg in $UB_PACKAGES; do
	for script in postinst postrm prerm; do
		if [ -f "$UB_SRCDIR/packages/$pkg/$script" ]; then
			install -m 755 "$UB_SRCDIR/packages/$pkg/$script" "$pkg/DEBIAN/$script-custom"
		fi
	done

	if ! grep -qx skip-postinst $UB_SRCDIR/packages/$pkg/options; then
		echo "#!/bin/bash" > "$pkg/DEBIAN/postinst"
		echo "" >> "$pkg/DEBIAN/postinst"
		echo "exec /usr/sbin/uhu-pkg postinst $pkg \"\$@\"" >> "$pkg/DEBIAN/postinst"
		chmod 755 "$pkg/DEBIAN/postinst"
	fi

	if ! grep -qx skip-postrm $UB_SRCDIR/packages/$pkg/options; then
		echo "#!/bin/bash" > "$pkg/DEBIAN/postrm"
		echo "" >> "$pkg/DEBIAN/postrm"
		echo "exec /usr/sbin/uhu-pkg postrm $pkg \"\$@\"" >> "$pkg/DEBIAN/postrm"
		chmod 755 "$pkg/DEBIAN/postrm"
	fi

	if ! grep -qx skip-prerm $UB_SRCDIR/packages/$pkg/options; then
		echo "#!/bin/bash" > "$pkg/DEBIAN/prerm"
		echo "" >> "$pkg/DEBIAN/prerm"
		echo "exec /usr/sbin/uhu-pkg prerm $pkg \"\$@\"" >> "$pkg/DEBIAN/prerm"
		chmod 755 "$pkg/DEBIAN/prerm"
	fi
done
