#!/bin/bash -eu

#
# Sztriptíz.
#
# A lényegi rész a dh_strip-ből puskázva. Aztán átalakítva:
#
# A lib-ekről csak a debug cuccokat sztripeljük (a la zsuzsi linux).
# Ettől alig lesznek nagyobbak (kb. 10%), de cserébe az
# nm progi kiírja a szimbólumokat, ami nagyon jó.
#

. /usr/lib/uhubuild/uhubuild-common

if grep -qx skip-strip "$UB_SRCDIR/options"; then
	echo " kihagyva"
	exit 0
fi

cd "$UB_INSTALLDIR"

find . -type f | while read file; do
	case "$(file -b "$file")" in
	  *ELF*executable*)
		echo "  $file"
		mode=$(stat -c '%a' "$file")
		chmod u+w "$file"
		pretendroot strip --strip-all "$file" || true
		chmod "$mode" "$file"
		;;
	  *shared*)
		echo "  $file"
		mode=$(stat -c '%a' "$file")
		chmod u+w "$file"
		pretendroot strip --strip-unneeded "$file" || true
		chmod "$mode" "$file"
		;;
	esac
done
find . -type f -name 'lib*.a' ! -name 'lib*_g.a' -print0 | while read -r -d $'\0' file; do
	echo "  $file"
	mode=$(stat -c '%a' "$file")
	chmod u+w "$file"
	pretendroot strip --strip-debug "$file" || true
	chmod "$mode" "$file"
done
