#!/bin/bash -eu

#
# Időcímke...
#

. /usr/lib/uhubuild/uhubuild-common

if [ -f "$UB_SRCDIR/changelog" ]; then
	find "$UB_PACKAGEDIR" -depth ! -type l -newer "$UB_SRCDIR/changelog" -print0 | \
	  xargs -0 -r touch -c -r "$UB_SRCDIR/changelog"
fi
