#!/bin/bash -eu

. /usr/lib/uhubuild/common

export UB_HOST="i686-uhu-linux"
export UB_MARCH="i686"
export UB_MTUNE="generic"
export UB_CFLAGS="-O2 -march=$UB_MARCH -mtune=$UB_MTUNE ${CFLAGS:-}"

export CFLAGS="$UB_CFLAGS"

argv=() # bash 4.3, declare -a: unbound variable
argx=(
	--prefix="/usr"             \
	--sysconfdir="/etc"         \
	--localstatedir="/var"      \
	--mandir="/usr/share/man"   \
	--infodir="/usr/share/info" \
	--enable-shared             \
	--build="$UB_HOST"          \
	--host="$UB_HOST"           \
)

if [ -z "${UB_CONFIGURE_NO_DISABLE_STATIC:-}" ]; then
		argx[${#argx[@]}]="--disable-static"
fi

shopt -s extglob

configure="${UB_CONFIGURE_SCRIPT:-${UB_CONFIGURE_DIR:-.}/configure}"

# add --disable-schemas-install if the configure script supports it
if grep -q disable-schemas-install "$configure"; then
		argx[${#argx[@]}]="--disable-schemas-install"
fi
# add --disable-scrollkeeper if the configure script supports it
if grep -q disable-scrollkeeper "$configure"; then
		argx[${#argx[@]}]="--disable-scrollkeeper"
fi

# libexecdir (/usr/libexec), sharedstatedir (/usr/com),
for i in "${argx[@]}"; do
	pattern="$i"
	pattern="${pattern/%=*/=*}"
	pattern="${pattern/#--@(en|dis)able-/--@(en|dis)able-}"
	pattern="${pattern/#--with?(out)-/--with?(out)-}"
	overridden="no"
	for arg in "$@"; do
		if [ "$i" == "$arg" ]; then
			warn "fölöslegesen megadott paraméter: [$arg]"
		fi
		case "$arg" in
			$pattern)
				overridden="yes"
				;;
		esac
	done
	if [ "$overridden" == "no" ]; then
		argv[${#argv[@]}]="$i"
	fi
done

# be verbose :)
echo "$configure"
for i in "$@" "${argv[@]}"; do
	echo -e "\t$i"
done
"$configure" "$@" "${argv[@]}"

if [ -n "${UB_UPDATELIBTOOL:-}" ]; then
	find . -name libtool -type f -print0 | while read -d $'\0' -r f; do
		cp -fv /usr/bin/libtool "$f"
	done
fi
