#!/bin/bash -eu

if [ -d "$UB_INSTALLDIR/usr/lib/perl5" ]; then
	find "$UB_INSTALLDIR/usr/lib/perl5" -name ".packlist" -type f  \
	-exec sed -e "s@^${UB_INSTALLDIR}@@g" {} \;
fi

if [ -d "$UB_INSTALLDIR/usr/lib/qt5" ]; then
	find $UB_INSTALLDIR/usr/lib/qt5/ -name \*.prl \
	-exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' \
				-e "s@^${UB_COMPILEDIR}@@g" -e "s@^${UB_INSTALLDIR}@@g" {} \;
	find $UB_INSTALLDIR/usr/lib/qt5/ -name \*.pri \
	-exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' \
				-e "s@^${UB_COMPILEDIR}@@g" -e "s@^${UB_INSTALLDIR}@@g" {} \;
fi

if [ -d "$UB_INSTALLDIR/usr/lib/q6" ]; then
	find $UB_INSTALLDIR/usr/lib/qt6/ -name \*.prl \
	-exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' \
				-e "s@^${UB_COMPILEDIR}@@g" -e "s@^${UB_INSTALLDIR}@@g" {} \;
	find $UB_INSTALLDIR/usr/lib/qt6/ -name \*.pri \
	-exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' \
				-e "s@^${UB_COMPILEDIR}@@g" -e "s@^${UB_INSTALLDIR}@@g" {} \;
fi
