#!/bin/bash -eu

if [ -f CMakeLists.txt -a -f build/Makefile ]; then
	cd build
fi

if [ -f Build.PL ]; then
	exec ./Build install destdir="$UB_INSTALLDIR"
fi

if [ -f setup.py -a ! -f Makefile ]; then
	exec python"${UB_PYTHON}" setup.py install --root="$UB_INSTALLDIR"
fi

if [ -f /usr/bin/scons -a -f SConstruct -a ! -f Makefile ]; then
	exec scons install --install-sandbox="$UB_INSTALLDIR" "$@"
fi

RPM_BUILD_ROOT="$UB_INSTALLDIR" \
ub_makeinstall "$@"

ub_fixpaths
